<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>network</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NapasSwitch.Routing\**\*.cs" />
    <None Remove="NapasSwitch.Routing\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NapasSwitch.Data\NapasSwitch.Data.csproj" />
  </ItemGroup>

</Project>